services:
  - type: web
    name: usr-web
    runtime: python
    buildCommand: python3 -m venv venv && venv/bin/pip install -r requirements.txt
    startCommand: venv/bin/gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
